music_directory		"~/Music"
# playlist_directory		"~/.config/mpd/playlists"
#log_file			"~/.config/mpd/log"
#pid_file			"~/.mpd/pid"
#state_file			"~/.mpd/state"
#sticker_file			"~/.mpd/sticker.sql"
bind_to_address "127.0.0.1"
#bind_to_address		"~/.mpd/socket"

auto_update	"yes"

database {
      plugin "simple"
      path "~/.local/share/mpd/db"
      cache_directory "~/.cache/mpd"
}

input {
        plugin "curl"
}

audio_output {
type		"pulse"
name		"My Pulse Output"
}
