require('nmqd.bootstrap')
require('nmqd.paq')
require('nmqd.keymap')
require('nmqd.options')
require('nmqd.autocmds')
require('nmqd.treesitter')
require('nmqd.telescope')
require('nmqd.mason')
require('nmqd.lsp')
require('nmqd.cmp')
require('nmqd.autopairs')
require('nmqd.comment')
require('nmqd.indent')
require('nmqd.lualine')
require('nmqd.colorizer')
require('nmqd.surround')
-- require('nmqd.dashboard')
require('nmqd.alpha')
